(ns markusfruhmann.constants
  (:require
   [markusfruhmann.utils :as utils]))

(def functions-regex
  [:* :+ :? :& :|])

(def arities-regex
  {:* 1
   :+ 1
   :? 1
   :& 2
   :| 2})

;; Each tomita grammars valid-words are defined using a regex representation from
;; Artificial Neural Networks and Machine Learning – ICANN 2019: Theoretical Neural Computation
;; by Igor V. Tetko, Věra Kůrková, Pavel Karpov, Fabian Theis
;; on page 315, table 1.
;; Each grammar contains 100 valid-words and 100 invalid-words.
;; The repetition of each regex function is increased to 50.

(def tomita-1-base {:valid-words ["aa"
                                  "a"
                                  "aaaaaa"
                                  "aaaaa"
                                  ""
                                  "aaa"
                                  "aaaa"]
                    :invalid-words ["ba"
                                    "bbba"
                                    "aab"
                                    "bba"
                                    "bbaaa"
                                    "bb"
                                    "aabb"
                                    "aabbab"
                                    "bbb"
                                    "aaab"
                                    "bab"
                                    "babb"
                                    "baaa"
                                    "baaaa"
                                    "b"
                                    "bbaa"
                                    "aabba"
                                    "baa"]})

(def tomita-2-base {:valid-words ["ab"
                                  "abab"]
                    :invalid-words ["bab"
                                    "baab"
                                    "abbaaaab"
                                    "abaab"
                                    "abbabbb"
                                    "abbaaa"
                                    "abbb"
                                    "bbaa"
                                    "bba"
                                    "abbab"
                                    "abbabbba"
                                    "aba"
                                    "aab"
                                    "abbaaaa"
                                    "bbaaa"
                                    "abbbaab"
                                    "abbba"
                                    "abaaaaab"
                                    "a"
                                    "abaaaa"
                                    "abbbaa"
                                    "ababa"
                                    "ba"
                                    "bbba"
                                    "bbab"
                                    "abbaaaabb"
                                    "abaa"
                                    "bbb"
                                    "abbaaab"
                                    "abaaaaa"
                                    "abb"
                                    "aababb"
                                    "bbbab"
                                    "b"
                                    "baa"
                                    "abaaa"
                                    "bb"
                                    "abbabb"
                                    "bbaaab"
                                    "aa"
                                    "aaab"
                                    "abbaa"
                                    "abbabbbab"
                                    "abba"
                                    "abaaaab"
                                    "aabab"
                                    "aaba"
                                    ""
                                    "aaa"]})

(def tomita-3-base {:valid-words ["babba"
                                  "baab"
                                  "abbaaa"
                                  "aaaaa"
                                  "aaaaaaa"
                                  "aab"
                                  "a"
                                  "aaaa"
                                  "ba"
                                  "aaaab"
                                  "babb"
                                  "babbaa"
                                  "abb"
                                  "aaaaaa"
                                  "b"
                                  "abbbb"
                                  "baa"
                                  "bb"
                                  "aa"
                                  "abbaa"
                                  "abba"
                                  "abbaabb"
                                  "aaba"
                                  ""
                                  "aaa"]
                    :invalid-words ["abbababaab"
                                    "abaabbbb"
                                    "ababaaaba"
                                    "bab"
                                    "abaabb"
                                    "abaaaaaa"
                                    "abaabbbbb"
                                    "abaab"
                                    "ababaa"
                                    "ab"
                                    "abaabbbbbaa"
                                    "abbb"
                                    "abaabbbbbaab"
                                    "ababaab"
                                    "abbab"
                                    "abbaaaba"
                                    "abbaaabaa"
                                    "babaaab"
                                    "aba"
                                    "baba"
                                    "abbaabaab"
                                    "aababa"
                                    "abbababa"
                                    "abbbaab"
                                    "abaabbbbba"
                                    "ababaaab"
                                    "abbba"
                                    "abbaaabaab"
                                    "abbbaa"
                                    "abaaaa"
                                    "abaaaaaab"
                                    "ababaaabab"
                                    "aababaab"
                                    "ababa"
                                    "ababab"
                                    "abaabbb"
                                    "abbaabbb"
                                    "babaaa"
                                    "abbaba"
                                    "abbaab"
                                    "abbabab"
                                    "babaa"
                                    "abaa"
                                    "babbaab"
                                    "abbaaab"
                                    "abaaaaa"
                                    "abbaaba"
                                    "aaaaaaab"
                                    "abbaabaa"
                                    "abaaab"
                                    "abbbab"
                                    "ababb"
                                    "abaaa"
                                    "aababaa"
                                    "aaab"
                                    "abab"
                                    "abaaaab"
                                    "ababaaa"
                                    "abbababaa"
                                    "aabab"]})

(def tomita-4-base {:valid-words ["bbabab"
                                  "bab"
                                  "aaabb"
                                  "bbabb"
                                  "abbaaa"
                                  "ab"
                                  "bba"
                                  "bbabaab"
                                  "a"
                                  "baaab"
                                  "ba"
                                  "bbab"
                                  "babb"
                                  "bbababa"
                                  "abbaaab"
                                  "abbaaabb"
                                  "bbabaabb"
                                  "abb"
                                  "b"
                                  "bbabababb"
                                  "bbabaa"
                                  "baa"
                                  "bbaba"
                                  "baaa"
                                  "bb"
                                  "aa"
                                  "aaab"
                                  "abbaa"
                                  "abba"
                                  "bbababab"
                                  ""
                                  "aaa"
                                  "baaabb"]
                    :invalid-words ["bbbbbaa"
                                    "bbbbb"
                                    "abbb"
                                    "bbbbbb"
                                    "bbbaaaba"
                                    "bbbaa"
                                    "baaabbb"
                                    "bbbbabb"
                                    "bbba"
                                    "bbbbaa"
                                    "bbb"
                                    "bbbab"
                                    "bbbaaabaa"
                                    "bbbaaab"
                                    "bbbb"
                                    "bbbabb"
                                    "bbbba"
                                    "bbbaaa"
                                    "bbbbab"
                                    "bbbbaab"
                                    "bbbbba"]})

(def tomita-5-base {:valid-words ["baba"
                                  "aababa"
                                  "bb"
                                  "aabb"
                                  "abbbaaba"
                                  "aa"
                                  "bbbbbb"
                                  "baab"
                                  "bbbb"
                                  "baabbaba"
                                  ""]
                    :invalid-words ["bab"
                                    "baabba"
                                    "aabbab"
                                    "babba"
                                    "aababab"
                                    "baabbab"
                                    "bbbbb"
                                    "ab"
                                    "abbb"
                                    "aabbabbb"
                                    "bba"
                                    "aba"
                                    "aab"
                                    "baabbabb"
                                    "abbbaab"
                                    "abbba"
                                    "babbb"
                                    "a"
                                    "abbbaa"
                                    "bbbbabb"
                                    "aabbabb"
                                    "aababbb"
                                    "baaab"
                                    "ba"
                                    "bbab"
                                    "babb"
                                    "bbb"
                                    "abb"
                                    "aababb"
                                    "b"
                                    "baa"
                                    "bbaba"
                                    "baaa"
                                    "bbbba"
                                    "bbbbab"
                                    "baabb"
                                    "aabab"
                                    "aaba"
                                    "aabba"
                                    "aaa"]})

(def tomita-6-base {:valid-words ["ba"
                                  "abbaab"
                                  "baba"
                                  "aabb"
                                  "bababa"
                                  "bbb"
                                  "baab"
                                  "abab"
                                  "babbb"
                                  "abba"
                                  "ababab"
                                  "ab"
                                  "abbbb"
                                  ""
                                  "aaa"
                                  "bababaab"]
                    :invalid-words ["bab"
                                    "aaabb"
                                    "abbbbb"
                                    "abbb"
                                    "aba"
                                    "aabbb"
                                    "aab"
                                    "a"
                                    "ababa"
                                    "babbbb"
                                    "babb"
                                    "abb"
                                    "b"
                                    "baa"
                                    "babbbbb"
                                    "bb"
                                    "aa"
                                    "aaab"
                                    "abbaa"
                                    "bababaa"
                                    "babab"]})

(def tomita-7-base {:valid-words ["bab"
                                  "aaabb"
                                  "abbbbb"
                                  "ab"
                                  "abbb"
                                  "bba"
                                  "aba"
                                  "aab"
                                  "abbbbba"
                                  "abbba"
                                  "a"
                                  "abbbaa"
                                  "ba"
                                  "bbab"
                                  "abaa"
                                  "abb"
                                  "aabaa"
                                  "aaabba"
                                  "b"
                                  "abbbb"
                                  "abbbba"
                                  "baa"
                                  "abaaa"
                                  "bb"
                                  "aa"
                                  "aaab"
                                  "abba"
                                  "aaba"
                                  ""
                                  "aaa"]
                    :invalid-words ["abaaaba"
                                    "aababab"
                                    "ababbbb"
                                    "abaab"
                                    "ababaa"
                                    "abbabaa"
                                    "aabaab"
                                    "ababaab"
                                    "abbab"
                                    "abababab"
                                    "abbbbab"
                                    "ababaabab"
                                    "aababa"
                                    "abbbaab"
                                    "abbabaab"
                                    "abbbbbab"
                                    "abababbbbab"
                                    "abababbbb"
                                    "ababaaaaaa"
                                    "ababa"
                                    "ababaaba"
                                    "ababab"
                                    "abbaba"
                                    "abababa"
                                    "ababbbbaba"
                                    "ababaaaaa"
                                    "ababbaba"
                                    "ababbabab"
                                    "abbbbaba"
                                    "ababba"
                                    "ababbab"
                                    "abaaba"
                                    "aaabbab"
                                    "abaaab"
                                    "ababbbbab"
                                    "abababbb"
                                    "abababbbba"
                                    "abbbab"
                                    "ababb"
                                    "ababbba"
                                    "ababbbbabab"
                                    "aabaabab"
                                    "abaaabab"
                                    "ababbbab"
                                    "abababb"
                                    "abab"
                                    "aabaaba"
                                    "ababaaa"
                                    "aabab"
                                    "ababbb"
                                    "abbbbabab"
                                    "ababaaaa"
                                    "abaabab"
                                    "ababbbba"]})

(def tomita-1 (utils/generate-word-map #"a*" #"(b+|a+b)+" tomita-1-base 100))
;; (def tomita-1 {:valid-words (gen/sample (sg/string-generator #"a*") 100)
;;                :invalid-words (gen/sample (sg/string-generator #"(b+|a+b)+") 100)})

(def tomita-2 (utils/generate-word-map #"(ab)*" #"(a+|b+)*a" tomita-2-base 100))
;; (def tomita-2 {:valid-words (gen/sample (sg/string-generator #"(ab)*") 100)
;;                :invalid-words (gen/sample (sg/string-generator #"(a+|b+)*a") 100)})

(def tomita-3 (utils/generate-word-map #"b*(((aa)+b*)|(a(aa)*(bb)+))*a?" #"b*((((aa)+b*)|(a(aa)*(bb)+))*(a(aa)*b(bb)*)+)+a?" tomita-3-base 100))
;; (def tomita-3 {:valid-words (gen/sample (sg/string-generator #"b*(((aa)+b*)|(a(aa)*(bb)+))*a?") 100)
;;                :invalid-words (gen/sample (sg/string-generator #"b*((((aa)+b*)|(a(aa)*(bb)+))*(a(aa)*b(bb)*)+)+a?") 100)})

(def tomita-4 (utils/generate-word-map #"(a|ba|bba)*(bb|b)?" #"(b*a*)*bbb(b*a*)*" tomita-4-base 100))
;; (def tomita-4 {:valid-words (gen/sample (sg/string-generator #"(a|ba|bba)*(bb|b)?") 100)
;;                :invalid-words (gen/sample (sg/string-generator #"(b*a*)*bbb(b*a*)*") 100)})

(def tomita-5 (utils/generate-word-map #"(aa|bb|(ab|ba)(aa|bb)*(ab|ba))*" #"(aa|bb|(ab|ba)(aa|bb)*(ab|ba))*(a|b)" tomita-5-base 100))
;; (def tomita-5 {:valid-words (gen/sample (sg/string-generator #"(aa|bb|(ab|ba)(aa|bb)*(ab|ba))*") 100)
;;                :invalid-words (gen/sample (sg/string-generator #"(aa|bb|(ab|ba)(aa|bb)*(ab|ba))*(a|b)") 100)})

(def tomita-6 (utils/generate-word-map #"(ba|(a|bb)(ab)*(b|aa))*" #"(ba|(a|bb)(ab)*(b|aa))*(b|a)" tomita-6-base 100))
;; (def tomita-6 {:valid-words (gen/sample (sg/string-generator #"(ba|(a|bb)(ab)*(b|aa))*") 100)
;;                :invalid-words (gen/sample (sg/string-generator #"(ba|(a|bb)(ab)*(b|aa))*(b|a)") 100)})

(def tomita-7 (utils/generate-word-map #"b*a*b*a*" #"(b+a+){3,}|(a+b+){2,}" tomita-7-base 100))
;; (def tomita-7 {:valid-words (gen/sample (sg/string-generator #"b*a*b*a*") 100)
;;                :invalid-words (gen/sample (sg/string-generator #"(b+a+){2,}|(a+b+){2,}") 100)})
